### ISSUE TITLE
Is it possible to stack the message sent by zc-bg-notify?

### ISSUE THREAD

**Issue by justinyhuang** [zdharma/zconvey#2]
maybe this is actually a feature request: would it be possible to stack the message sent by zc-bg-notify?

for example: after sending a message "build is done" all the terminals will see:

/>
Notification: build is done

and then later after sending a new message "test is done" all the terminals now look like:

/>
Notification: build is done
Notification: test is done

and if the use run some new commands or just return, the notifications will go away.

Thanks!

**Comment by psprint** [comment]
I've implemented this, thanks. I only stack the notifications in opposite order – more recent ones are on top.
